import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { ThemeService } from '../../services/theme.service';
import { LucideAngularModule } from 'lucide-angular';

@Component({
  selector: 'app-about',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  templateUrl: './about.component.html',
  styleUrl: './about.component.css'
})
export class AboutComponent {
  router = inject(Router);
  theme = inject(ThemeService);

  features = [
    { icon: '🧠', title: 'AI-Powered Cleanup', desc: 'Gemini AI reads your inbox structure and identifies subscriptions, promotions, and OTP codes for one-click removal.' },
    { icon: '🔐', title: 'OAuth-Only Access', desc: 'We never store your password. All Gmail access is granted via Google\'s industry-standard OAuth 2.0 protocol.' },
    { icon: '⚡', title: 'Background Jobs', desc: 'Bull MQ queue ensures cleanup tasks run asynchronously, so your experience stays snappy even for large inboxes.' },
    { icon: '📅', title: 'Smart Calendar', desc: 'Detects meeting invites and time references in emails and suggests Google Calendar events automatically.' },
    { icon: '✍️', title: 'AI Draft Replies', desc: 'Tone-matched draft replies generated by Gemini directly inserted into your Gmail Drafts folder.' },
    { icon: '🛡️', title: 'Zero Data Retention', desc: 'Email content is processed in-memory and never written to our servers. Your privacy is non-negotiable.' },
  ];
}
